- hosts: localhost
  tasks:
  - name: Set the stable docker repository
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge"
    state: present
    update_cache: yes    
  - name: Start docker service
    service:
      name: docker
      state: started
